### ISSUE TITLE
Tidyverse isn't really "importable"

### ISSUE THREAD

**Issue by lkhilton** [morinlab/GAMBLR#102]
I noticed today when testing Ryan's GAMBLR remote files that `get_gambl_metadata()` throws an error if `tidyverse` hasn't been explicitly loaded, even though it's listed as a dependency. 

Turns out tidyverse isn't importable in this way and you are supposed to import individual packages from within tidyverse. 

https://stackoverflow.com/a/62377442/16737334

**Comment by rdmorin** [comment]
Do we import the actual packages now instead?

**Comment by mattssca** [comment]
Not for all functions, I will go over the outstanding functions in an upcoming PR. So not resolved yet.
