### ISSUE TITLE
get_ssm_by_regions() is duplicating variants, and assigning them to the incorrect regions

### ISSUE THREAD

**Issue by ckrushton** [morinlab/GAMBLR#106]
Running ```get_ssm_by_regions(grch37_ashm_regions)``` yields the following dataframe:

![image](https://user-images.githubusercontent.com/22357668/175650149-5ec5f1e4-f654-49d1-9a5a-42862c6a9873.png)

For some reason, this function is only returning variants upstream of MYC, and assigning them to (seemingly) ALL regions provided

![image](https://user-images.githubusercontent.com/22357668/175650730-d8e11ea0-d20f-45d6-800f-89e2b41857a9.png)

**Comment by rdmorin** [comment]
@mattssca already fixed this issue. Here's how I run it and it works on my branch. Waiting for that PR to be merged, unfortunately. 
```
all_dlbcl_genome_ashm = get_ssm_by_regions(regions_bed=regions_bed,seq_type="genome",streamlined = F)
```

**Comment by mattssca** [comment]
The PR with a fix for this has now been merged into Master
