### ISSUE TITLE
Issues with the `collate_sbs_results` part of `collate_results`

### ISSUE THREAD

**Issue by lkhilton** [morinlab/GAMBLR#113]
`collate_results` uses the cached results table by default. This is good because it has preserved mutational signature data that has since gone away (namely the current mutational signature table omits SBS9 which has to be the worst one to omit from GAMBL). 

However the `sbs_manipulation` argument effectively does nothing with the cached results because only SBS1, 8, and 9 have scaled results cached, so all the other mutational signatures have only original data preserved. Also I think expected behavior is that if the user wants scaled data returned, the function should ONLY return scaled data, not scaled + unscaled data in cryptically named columns.

**Comment by Kdreval** [comment]
I will migrate this issue to the appropriate child repo
