### ISSUE TITLE
Make `get_gene_expression` work for non-`morinlab` users

### ISSUE THREAD

**Issue by lkhilton** [morinlab/GAMBLR#123]
Currently the `get_gene_expression` function only works for users with `morinlab` group permissions because the config accesses only `icgc_dart` outputs. I've now updated my salmon/DESeq2 Snakefile to also generate the tidy gene expression matrix for each unix_group. Could you please update the function to use either the `gambl` version or `icgc_dart` version depending on a user's permission levels? 

For those with `morinlab` permissions the file will be `results/icgc_dart/DESeq2-0.0_salmon-1.0/mrna--gambl-icgc-all/vst-matrix-Hugo_Symbol_tidy.tsv` (i.e. current status quo)

For those with only `gambl` permissions the file will be `results/gambl/DESeq2-0.0_salmon-1.0/mrna/vst-matrix-Hugo_Symbol_tidy.tsv`

Also, now that the Salmon Snakefile has been set up to generate the tidy matrix, we should consider modifying the current `tidy_gene_expression` function to NOT write to file by default as this will create some conflicts with the Snakefile version.

**Comment by mattssca** [comment]
Thanks @lkhilton the issue detailed above is addressed in [this](https://github.com/morinlab/GAMBLR/commit/d1a2618dccbebf06f427e0bd5dcb65eb36d3e33a) commit
