### ISSUE TITLE
`annotate_driver_ssm` has the wrong argument name

### ISSUE THREAD

**Issue by lkhilton** [morinlab/GAMBLR#126]
The function `annotate_driver_ssm` calls for the following arguments: 
```
function (maf_df, lymphoma_type, driver_genes, noncoding_regions = c(NFKBIZ = "chr3:101578206-101578365", 
    HNRNPH1 = "chr5:179,045,946-179,046,683")) 
```
Within the function body, the non-coding argument is referenced as `include_noncoding`. 

This should be updated so the function can read from its arguments.

**Comment by mattssca** [comment]
Thanks for reporting this bug @lkhilton this has been addressed in [this](https://github.com/morinlab/GAMBLR/commit/9b9e8536a182adeda0f8d7b09273ce195f3fcf19) commit.
