### ISSUE TITLE
GAMBLR documentation formatting is incorrect for many functions

### ISSUE THREAD

**Issue by rdmorin** [morinlab/GAMBLR#128]
It looks like the description is being interpreted as the title for some functions because there is not a separate title line in the documentation. I've fixed this for a few functions but I'm sure it's a problem elsewhere. Here's one I fixed. Originally it had all the text on the first line, which caused ROxygen to use that as the title and the description, which cluttered the docs page due to the font size and duplication. Be sure all functions either have a sufficiently brief title that this isn't a concern OR (ideally) all have both a title and description, separated by an empty line. 

```
#' Get MAF-format data frame for more than one sample and combine together
#' 
#' This function internally runs get_ssm_by_sample. See get_ssm_by_sample for more information
#' 
#' @param these_sample_ids A vector of sample_id that you want results for. 
```

**Comment by mattssca** [comment]
(This will also be addressed in a PR I am working on)

**Comment by rdmorin** [comment]
Since this is still open I thought it worth mentioning that some of the documentation is not very clear. Reading the docs for this function actually doesn't tell me what it's doing. 

fancy_alignment_plot
Description
Visualize (stacked barplot) genomic read-subsets across a selection of samples.

**Comment by rdmorin** [comment]
I also found another function with the formatting still messed up:



fancy_cnbar

**Comment by mattssca** [comment]
Yes, thanks!

**Comment by rdmorin** [comment]
For an example of how MAFtools documentation handles this check out the first function here:

https://github.com/PoisonAlien/maftools/blob/master/R/oncoplot.R

**Comment by mattssca** [comment]
Yes, I am aware that pretty much every function description needs to be updated in order for us to close this issue. I think It's been a rather low priority, but I will see to it that this gets taken care of in my upcoming PR
