### ISSUE TITLE
get_cn_segments is broken

### ISSUE THREAD

**Issue by rdmorin** [morinlab/GAMBLR#136]
It looks like the only way the get_cn_segments function works is when the database is used. The from_flatfile option is available but when I try supplying it I get an error:

```
my_segments = get_cn_segments(region="chr8:128,723,128-128,774,067",from_flatfile=TRUE)
 Error in rbind(all_segs_matched, all_segs_unmatched) : 
object 'all_segs_matched' not found
```

**Comment by mattssca** [comment]
Thanks for posting an issue of this. I will look into this.
