### ISSUE TITLE
Remove hardcoding in collate_csr_results 

### ISSUE THREAD

**Issue by rdmorin** [morinlab/GAMBLR#139]
The path to the file loaded by collate_csr_results is hard-coded. This should be changed to use the config and the path where this file lives should also be somewhere central. We can discuss in a GAMBL meeting what location makes the most sense.
```
collate_csr_results = function(sample_table,seq_type_filter = "genome"){
   if(seq_type_filter=="capture"){
     return(sample_table) #result doesn't exist or make sense for this seq_type
   }
   csr = suppressMessages(read_tsv("/projects/rmorin/projects/gambl-repos/gambl-nthomas/results/icgc_dart/mixcr_current/level_3/mixcr_genome_CSR_results.tsv"))
...
```

**Comment by Kdreval** [comment]
I will migrate this issue to the appropriate child repo
