### ISSUE TITLE
Documentation errors during install

### ISSUE THREAD

**Issue by rdmorin** [morinlab/GAMBLR#178]
Running devtools::install() with the Master branch gives this output. Can this be addressed?

Enter one or more numbers, or an empty line to skip updates: 
✔  checking for file ‘/Users/rmorin/git/GAMBLR/DESCRIPTION’ ...
─  preparing ‘GAMBLR’: (470ms)
✔  checking DESCRIPTION meta-information ...
   Warning: bad markup (extra space?) at chromosome_arms_grch37.Rd:16:2
   Warning: /private/var/folders/kk/mjt9hn3n7nn25nfvhv6mkjm40000gn/T/Rtmpk0nEGf/Rbuildab634845df0c/GAMBLR/man/chromosome_arms_grch37.Rd:19: unexpected section header '\usage'
   Warning: /private/var/folders/kk/mjt9hn3n7nn25nfvhv6mkjm40000gn/T/Rtmpk0nEGf/Rbuildab634845df0c/GAMBLR/man/chromosome_arms_grch37.Rd:22: unexpected section header '\description'
   Warning: /private/var/folders/kk/mjt9hn3n7nn25nfvhv6mkjm40000gn/T/Rtmpk0nEGf/Rbuildab634845df0c/GAMBLR/man/chromosome_arms_grch37.Rd:25: unexpected section header '\keyword'
   Warning: /private/var/folders/kk/mjt9hn3n7nn25nfvhv6mkjm40000gn/T/Rtmpk0nEGf/Rbuildab634845df0c/GAMBLR/man/chromosome_arms_grch37.Rd:26: unexpected END_OF_INPUT '
   '
   Warning: bad markup (extra space?) at chromosome_arms_hg38.Rd:16:2
   Warning: /private/var/folders/kk/mjt9hn3n7nn25nfvhv6mkjm40000gn/T/Rtmpk0nEGf/Rbuildab634845df0c/GAMBLR/man/chromosome_arms_hg38.Rd:19: unexpected section header '\usage'
   Warning: /private/var/folders/kk/mjt9hn3n7nn25nfvhv6mkjm40000gn/T/Rtmpk0nEGf/Rbuildab634845df0c/GAMBLR/man/chromosome_arms_hg38.Rd:22: unexpected section header '\description'
   Warning: /private/var/folders/kk/mjt9hn3n7nn25nfvhv6mkjm40000gn/T/Rtmpk0nEGf/Rbuildab634845df0c/GAMBLR/man/chromosome_arms_hg38.Rd:25: unexpected section header '\keyword'
   Warning: /private/var/folders/kk/mjt9hn3n7nn25nfvhv6mkjm40000gn/T/Rtmpk0nEGf/Rbuildab634845df0c/GAMBLR/man/chromosome_arms_hg38.Rd:26: unexpected END_OF_INPUT '

**Comment by Kdreval** [comment]
I picked up this issue too. This is already fixed in PR #177 That PR is ready for review

**Comment by Kdreval** [comment]
The fix is now merged to master
