### ISSUE TITLE
Unhelpful error when nonexistent patient_id is provided to get_coding_ssm

### ISSUE THREAD

**Issue by rdmorin** [morinlab/GAMBLR#179]
Can someone figure out how to catch this type of error and warn the user with something more informative than what R spits out?
```
get_coding_ssm(these_samples_metadata = dplyr::filter(all_meta,patient_id=="MORON"))
reading from: /Users/rmorin/gambl_results/
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.data.frame': File '/Users/rmorin/gambl_results/' is a directory. Not yet implemented.
  ```

**Comment by rdmorin** [comment]
The same error happens if the user specifies a sample_id that doesn't exist in the metadata.

**Comment by mattssca** [comment]
I'll self-assign this issue. Thanks for reporting it, Ryan.

**Comment by mattssca** [comment]
I'll self-assign this issue. Thanks for reporting it, Ryan.
