### ISSUE TITLE
Using GAMBLR with no remote/GAMBL access requires set up

### ISSUE THREAD

**Issue by ninaliuta** [morinlab/GAMBLR#183]
I’m currently using GAMBLR locally on my computer and I don’t have GAMBL/remote access. I’m getting this error when I run `get_gambl_metadata` because it’s not currently set up to access metadata locally. Any suggestions to make GAMBLR local-user friendly? Thank you!
```
> this_metadata = get_gambl_metadata(seq_type_filter = "genome")
[1] "missing:  /Users/rmorin/git/gambl/data/metadata/gambl_all_outcomes.tsv"
Have you cloned the GAMBL repo and added the path to this directory under the local section of your config?
Error: '/Users/rmorin/git/gambl/data/metadata/gambl_all_outcomes.tsv' does not exist.
```

**Comment by Kdreval** [comment]
This is now solved with a paired object `GAMBLR.data::gambl_metadata` and can be retrieved with `GAMLR.data::get_gambl_metadata()`.
Closing the issue as completed.
