### ISSUE TITLE
GAMBLR Function Examples

### ISSUE THREAD

**Issue by mattssca** [morinlab/GAMBLR#187]
I’ve reviewed the examples listed under the function documentation in GAMBLR. The examples have been updated so that each function has fully reproducible examples from start to finish. This includes code for how the input data is meant to be retrieved and/or any necessary data wrangling to present the data in a format that is acceptable by the function. I think and hope that this will improve the overall understanding of how a function is meant to be used.

This task was done as a first step in getting ready to build a website from the GAMBLR source code with `pkgdown`. When doing so, the `build_site()` from this package, executes all the function examples and generates function-specific html files, complete with the output and function description sections (title, description, details, parameters, imports, return, examples), think of it as a mini-vignette for each function. 

With this being said, there are a few outstanding functions that still needs meaningful and more importantly, working examples.

It would be much appreciated if I could get some input on the following functions. If you are the author of any of these functions, perhaps you could provide me with an example. 

Feel free to post your examples on this issue and I will add them to my PR. 

### These are the functions:

**preprocessing_io.R**

- [x] find_expected_outputs
- [x] fetch_output_files

**utilities.R**

- [x] compare_mutation_flavour 
- [x] sanitize_maf_data
- [x] estiamte_purity
- [x] get_bams
- [x] make_igv_snapshot
- [x] FtestCNV
- [x] cleanup_maf

**viz.R**

- [x] plot_mutation_dynamics_heatmap
- [x] prettyChromoplot
- [x] splendidHeatmap

**Comment by Kdreval** [comment]
I can work on generating examples for some of these functions 👍

**Comment by mattssca** [comment]
Awesome, thanks Kostia! Feel free to tick the box for the functions your self-assigning :)
