### ISSUE TITLE
`get_gambl_metadata` is broken for normals

### ISSUE THREAD

**Issue by lkhilton** [morinlab/GAMBLR#190]
When I try to run `get_gambl_metadata(tissue_status_filter = "normal")` I get the following error: 
```
Error in `mutate_cols()`:          
! Problem with `mutate()` column `consensus_coo_dhitsig`.
ℹ `consensus_coo_dhitsig = case_when(...)`.
✖ must be a logical vector, not a character vector.
Caused by error in `glubort()`:
! must be a logical vector, not a character vector.
Run `rlang::last_trace()` to see where the error occurred.
```

I think this can be traced back to commit [c752dfb](https://github.com/morinlab/GAMBLR/commit/c752dfb9b2aef1332ddbff772ab4ecffcda90983#diff-ceac008e84479617838e43ccee62a841a40d638bfb2f9221382c61c9e5e82eefL600-R603), which commented out the part that simply returns the basic metadata columns when `normal` is the requested tissue_status. Could someone look into this? 

This is with the current master eecaa88.

**Comment by lkhilton** [comment]
Could @mattssca take a look at the change that broke this functionality?

**Comment by mattssca** [comment]
Yes, let me have a look!

**Comment by lkhilton** [comment]
Yay, thank you!

**Comment by lkhilton** [comment]
@mattssca there is still a bug with this function, unfortunately. If you specify both tumour and normal (e.g. `tissue_status_filter = c("tumour", "normal")`), it returns this error: 
```
get_gambl_metadata(tissue_status_filter = c("tumour","normal"))
Error in if (tissue_status_filter == "normal") { :                                                                                                                                                                                
  the condition has length > 1
```

This is because [this test](https://github.com/morinlab/GAMBLR/blame/104ed3b1a69003d737b681c3d593317cebd5eb4d/R/database.R#L678C3-L680C4) requires that `tissue_status_filter` is a vector of length 1. I think you need to include a test of the vector length first, e.g. 
```
if (length(tissue_status_filter) == 1 & tissue_status_filter == "normal")
```
