### ISSUE TITLE
Based on the description in the tutorial, what is the purpose of collate_results?

### ISSUE THREAD

**Issue by rdmorin** [morinlab/GAMBLR#204]
We need to be more explicit in some of the examples in the tutorials. One I came across was collate_results. As someone who has never used that function, the description in the tutorial doesn't really give a sense of what this function is for. All the text after this sentence relates only to the various ways to run the function. 

```
Another useful function for collecting all derived sample-level results from a variety of GAMBL pipelines is to call collate_results. 
```

**Comment by mattssca** [comment]
Thanks for reporting this. I can update the vignette to be more informative in regard to the purpose of this function.
