### ISSUE TITLE
Error thrown by prettyGeneCloud example

### ISSUE THREAD

**Issue by rdmorin** [morinlab/GAMBLR#205]
The call to `prettyGeneCloud` in the examples seems to throw an error. 

https://morinlab.github.io/GAMBLR/reference/prettyGeneCloud.html

```
#build wordcloud
prettyGeneCloud(maf_df = maf, these_genes = my_genes)
#> Error in dplyr::filter(maf_df, Hugo_Symbol %in% these_genes): Problem while computing `..1 = Hugo_Symbol %in% these_genes`.
#> Caused by error in `h()`:
#> ! error in evaluating the argument 'table' in selecting a method for function '%in%': object 'my_genes' not found
```

**Comment by mattssca** [comment]
Interesting that build_site never warned about this. The reason for this error seems to be that the function `pull` can not be found. Thanks for finding this, I will udpate this function with a working example. I will also have a look at the other function-specific HTMLs to make sure no other examples are erroring out.

**Comment by mattssca** [comment]
The example has been updated, package docs regenerated, and the website rebuilt in [this](https://github.com/morinlab/GAMBLR/pull/196) PR.
