### ISSUE TITLE
some issues with vignettes

### ISSUE THREAD

**Issue by rdmorin** [morinlab/GAMBLR#209]
Some of the outputs in our vignettes don't look right on the website. Can this be addressed?
e.g.
https://morinlab.github.io/GAMBLR/articles/utilities_tutorial.html#compare-cnvs-for-multiple-samples
The heatmap in this example has many cluttered/overlapping column labels. 

https://morinlab.github.io/GAMBLR/articles/ssm_tutorial.html#lollipop-plot
I don't see a lollipop plot in this example (just an empty white space)

https://morinlab.github.io/GAMBLR/articles/ssm_tutorial.html#rainbow-plots
Does aSHM multi-rainbow plot print out the entire data frame of regions by default? If so, this should be shifted to functionality that only happens in a "verbose" mode because the table shown in the vignette is huge and probably unnecessary.

**Comment by mattssca** [comment]
Thanks, Ryan, I'll go over these. I knew there are a few weird formatting issues with the figures that I also hope to resolve.
