### ISSUE TITLE
annotate MAF with triplet context

### ISSUE THREAD

**Issue by rdmorin** [morinlab/GAMBLR#222]
Can we add functionality to GAMBLR to allow users to annotate MAFs with the triplet context (mutated base with adjacent -1 and +1)? Ideally we should also support (optionally) converting to the reverse complement according to the direction of transcription. 

e.g.
Mutation
C>T
Hypothetical triplet sequence context extracted from reference genome:
GCA
If the affected gene is on the opposite strand:
TGC

**Comment by rdmorin** [comment]
@HoumanLM is this complete?

**Comment by HoumanLM** [comment]
@rdmorin I pushed the new code, I need your confirmation to start modifying its documentation. Then, it will be okay!

**Comment by HoumanLM** [comment]
Now, I believe this issue has also been posted in the following link:
https://github.com/morinlab/GAMBLR.results/issues/24
