### ISSUE TITLE
Update/complete/fix missing/old documentation

### ISSUE THREAD

**Issue by rdmorin** [morinlab/GAMBLR#51]
Many GAMBLR functions have a disconnect between their documentation and actual current set of arguments. We need to make a concerted effort to backfill this information and correct it where necessary.

- remove arguments from documentation when they are no longer available
- add missing arguments
- add description for arguments that are not described

**Comment by mattssca** [comment]
The issues described above have been addressed in the commits on [this ](https://github.com/morinlab/GAMBLR/tree/cmattsson/GAMLBR-code-review) branch
