### ISSUE TITLE
Identify helper/internal and obsolete functions.

### ISSUE THREAD

**Issue by mattssca** [morinlab/GAMBLR#56]
We need to go over the functions listed in each of the R scripts, to highlight functions that should be considered as helper/internal and unused functions (i.e not export to NAMESPACE and update function description accordingly). A suggested approach could be to list such functions in the comment section of this issue, I could then update the scripts accordingly and link the PR in the comments.

**Comment by Kdreval** [comment]
These functions can be considered helpers/internal and are not meant for out-of-package usage:

```
export(add_icgc_metadata)
export(append_to_table)
export(assemble_file_details)
export(collate_ashm_results)
export(collate_csr_results)
export(collate_curated_sv_results)
export(collate_nfkbiz_results)
export(collate_sbs_results)
export(collate_ssm_results)
export(collate_sv_results)
export(fetch_output_files)
export(finalize_study)
export(find_expected_outputs)
export(find_files_extract_wildcards)
export(get_gambl_outcomes)
export(map_metadata_to_colours)
export(populate_each_tool_result)
export(populate_tool_results)
export(process_all_manta_bedpe)
export(referesh_metadata_tables)
export(refresh_full_table)
export(region_to_chunks)
export(setup_fusions)
export(setup_study)
export(trim_scale_expression)
```

**Comment by mattssca** [comment]
Thanks, Kostia! I will go over the R scripts and update the function description for above mentioned internal functions. Stay tuned.

**Comment by mattssca** [comment]
Description for internal functions has been updated to state the function type and also what exported function that calls the described internal function. For example, in the description of `map_metadata_to_colours` the following line is added at the top of the description: `#' INTERNAL FUNCTION called by plot_sample_circos and get_mutation_frequency_bin_matrix, not meant for out-of-package usage.`. In addition, internal functions have been removed from NAMESPACE.

The following internal functions have been updated:


- add_icgc_metadata
- append_to_table
- collate_ashm_results
- collate_csr_results
- collate_curated_sv_results
- collate_nfkbiz_results
- collate_sbs_results
- collate_ssm_results
- collate_sv_results
- get_gambl_outcomes
- map_metadata_to_colours

There are some outstanding internal functions (in portal.R and preprocessing_io.R) that needs to be updated after these scripts have been revised. The outstanding functions are:

- fetch_output_files
- assemble_file_details
- finalize_study
- find_expected_outputs
- find_files_extract_wildcards
- populate_each_tool_result
- populate_tool_results
- process_all_manta_bedpe
- setup_fusions
- setup_study

The issue will be closed once the outstanding functions are updated.

**Comment by mattssca** [comment]
Functions in portal.R have been updated accordingly and the remaining functions in preprocessing_io.R are deprecated and handled elsewhere.
