### ISSUE TITLE
ensure Morinlab fork of g3viz is installed as a dependency

### ISSUE THREAD

**Issue by rdmorin** [morinlab/GAMBLR#62]
It seems that the auto-installation of dependencies is relying on the main g3viz version, which doesn't handle MAFs the way we need for certain functions. For some GAMBLR functions to work we need users to have the version here:

https://github.com/morinlab/g3viz

Can GAMBLR be set up to automatically install from this fork?

**Comment by mattssca** [comment]
I believe this can be done by adding the following lines to GAMBLR DESCRIPTION:

Remotes:
github::morinlab/g3viz

And then just add g3viz under Imports: section.

I am doing some testing...
