### ISSUE TITLE
Vignette refers to some functionality that is deprecated or gone

### ISSUE THREAD

**Issue by rdmorin** [morinlab/GAMBLR#77]
The vignette needs a lot of TLC. There are many sections relating to the database that are obsolete at this point. There is at least one function used in an example that doesn't exist in the current version of GAMBLR. This should be removed or updated to use the new functionality 

```
```{r ssms_and_maftools, out.width = "100%", fig.dim = c(8,3)}
all_ssms = get_ssm_by_gene(gene_symbol = c("CCND3"), coding_only = TRUE)

all_ssms = all_ssms %>%
  as.data.frame()

# Make a MAFtools object and plot a lollipop plot
maf_obj = read.maf(all_ssms)
lollipopPlot(maf_obj, gene = "CCND3")
```
```

**Comment by mattssca** [comment]
This specific function has been updated to use geet_coding_ssm instead of the no longer available function get_ssm_by_gene. Outstanding issues with functions relying on the database will be addressed in an upcoming PR. Stay tuned...

**Comment by mattssca** [comment]
This was fixed in [this](https://github.com/morinlab/GAMBLR/pull/85) PR
