### ISSUE TITLE
ashm_multi_rainbow_plot broken?

### ISSUE THREAD

**Issue by rdmorin** [morinlab/GAMBLR#80]
The example for this function in our vignette produces just a very busy legend. 

<img width="818" alt="image" src="https://user-images.githubusercontent.com/4723139/162508703-2d2db67a-3b1a-4b9e-bdbe-fcb524a7bd77.png">

**Comment by rdmorin** [comment]
I think this is related to ggplot changing the behaviour of scale_X_manual functions, as per:

https://community.rstudio.com/t/scale-colour-manual-does-not-drop-unused-levels/109094/4

**Comment by rdmorin** [comment]
Confirmed that installing ggplot2 from github resolves this. Not really an ideal solution.

**Comment by Kdreval** [comment]
I have added  a solution for this in #73 that will always sunset colors to the keys actually present in the data ✅
