### ISSUE TITLE
get_ssm_by_region incorrectly subsets on five columns, regardless if basic_column is TRUE

### ISSUE THREAD

**Issue by mattssca** [morinlab/GAMBLR#97]
This function needs to be updated so that all MAF columns are retained. 

Currently, the function subsets on Chromosome, Start_Position, End_Position, Tumor_Sample_Barcode and Read_Support when reading indexed maf. Thus, using basic_columns = TRUE cannot subset on columns 1-45 throws an error. 

This function can possibly be simplified using the [Vroom](https://www.tidyverse.org/blog/2019/05/vroom-1-0-0/) package to read data into R.

**Comment by rdmorin** [comment]
I think I've gotten this issue sorted out now (waiting on the PR to get into Master).
